library(faraway)
data(pulp)
attach(pulp)
with(pulp, stripchart(bright~operator,vertical=TRUE, method="stack",xlab="operator",ylab="bright"))
med <- with(pulp, tapply(bright,operator, median))
ha <- with(pulp,abs(bright-med[operator]))
anova(lm(ha ~ operator, data = pulp))
ppx<-lm(bright ~ operator - 1, data = pulp)
summary(ppx)
TukeyHSD(aov(bright ~ operator,pulp))
detach(pulp)
