library(faraway)
data(PlantGrowth)
attach(PlantGrowth)
with(PlantGrowth, stripchart(weight ~ group,vertical=TRUE, method="stack",xlab="group",ylab="weight"))
med <- with(PlantGrowth, tapply(weight, group, median))
ha <- with(PlantGrowth, abs(weight - med[group]))
anova(lm(ha ~ group, PlantGrowth))
plant <- lm(weight ~ group, data = PlantGrowth)
summary(plant)
TukeyHSD(aov(weight ~ group, PlantGrowth))
groupa <- c(rep("control",10),rep("treay",20))
plantdata <- data.frame(PlantGrowth, groupa)
planta <- lm(weight ~ groupa, plantdata)
summary(planta)
TukeyHSD(aov(weight ~ groupa, plantdata))
t.test(plantdata$weight[1:10], plantdata$weight[11:30])
detach(PlantGrowth)
