library(faraway)
data("teengamb")
summary(teengamb)
g<-lm(gamble ~ . + sex:(status+income+verbal),teengamb)
summary(g)
g2<-lm(gamble ~ sex+status*sex+income+verbal,teengamb)
summary(g2)
g3<-lm(gamble ~ sex+status+income:sex+verbal,teengamb)
summary(g3)
g4<-lm(gamble ~ sex+status+income+verbal:sex,teengamb)
summary(g4)
paste("We can see from g2, it reveals that these factors are significant and that sex is related to status")
